import 'package:nalelu/na_helpers.dart';

var kanjiBank = [
  Kanji(
    translation: NA.t('一'),
    kanji: '一',
    onYomi: 'イチ',
    kunYomi: 'ひと / ひと-つ',
    phrases: ['一つ', '一人', '一日'],
    answers: ['ひと', 'ひと', 'いち'],
  ),
  Kanji(
    translation: NA.t('二'),
    kanji: '二',
    onYomi: 'ニ',
    kunYomi: 'ふた / ふた-つ',
    phrases: ['二月', '二つ', '十二月'],
    answers: ['に', 'ふた', 'に'],
  ),
  Kanji(
    translation: NA.t('三'),
    kanji: '三',
    onYomi: 'サン / ゾウ',
    kunYomi: 'み / み-つ / みっ-つ',
    phrases: ['三月', '三日', '三つ'],
    answers: ['さん', 'みっ', 'みっ'],
  ),
  Kanji(
    translation: NA.t('四'),
    kanji: '四',
    onYomi: 'シ',
    kunYomi: 'よ / よ-つ / よっ-つ',
    phrases: ['四月', '四日', '四つ'],
    answers: ['し', 'よっ', 'よっ'],
  ),
  Kanji(
    translation: NA.t('五'),
    kanji: '五',
    onYomi: 'ゴ',
    kunYomi: 'いつ / いつ-つ',
    phrases: ['五つ', '五月', '五円'],
    answers: ['いつ', 'ご', 'ご'],
  ),
  Kanji(
    translation: NA.t('六'),
    kanji: '六',
    onYomi: 'ロク',
    kunYomi: 'む / む-つ / むっ-つ',
    phrases: ['六つ', '六月', '六日'],
    answers: ['むっ', 'ろく', 'むい'],
  ),
  Kanji(
    translation: NA.t('七'),
    kanji: '七',
    onYomi: 'シチ',
    kunYomi: 'なな / なの',
   phrases: ['七つ', '七月', '七日'],
    answers: ['なな', 'しち', 'なの'],
  ),
  Kanji(
    translation: NA.t('八'),
    kanji: '八',
    onYomi: 'ハチ',
    kunYomi: 'や / や-つ / やっ-つ',
     phrases: ['八つ', '八月', '八日'],
    answers: ['やっ', 'はち', 'よう'],
  ),
  Kanji(
    translation: NA.t('九'),
    kanji: '九',
    onYomi: 'キュウ / ク',
    kunYomi: 'ここの / ここの-つ',
   phrases: ['九つ', '九月', '九日'],
    answers: ['ここの', 'く', 'ここの'],
  ),
  Kanji(
    translation: NA.t('十'),
    kanji: '十',
    onYomi: 'ジュウ',
    kunYomi: 'とお',
    phrases: ['十月', '十日', '十分な'],
    answers: ['じゅう', 'とお', 'じゅう'],
  ),
  Kanji(
    translation: NA.t('百'),
    kanji: '百',
    onYomi: 'ヒャク',
    kunYomi: 'もも',
    phrases: ['百', '三百'],
    answers: ['ひゃく', 'びゃく'],
  ),
  Kanji(
    translation: NA.t('千'),
    kanji: '千',
    onYomi: 'セン',
    kunYomi: 'ち',
    phrases: ['千', '三千'],
    answers: ['せん', 'ぜん'],
  ),
  Kanji(
    translation: NA.t('万'),
    kanji: '万',
    onYomi: 'マン / バン',
    kunYomi: 'よろず',
    phrases: ['一万'],
    answers: ['まん'],
  ),
  Kanji(
    translation: NA.t('円'),
    kanji: '円',
    onYomi: 'エン',
    kunYomi: 'まる / まるい / まど / まどか',
    phrases: ['円', '四万円'],
    answers: ['えん', 'えん'],
  ),
  Kanji(
    translation: NA.t('日'),
    kanji: '日',
    onYomi: 'ニチ / ジツ',
    kunYomi: 'ひ / か / か-つ / か-れる',
    phrases: ['日本', '日', '休日'],
    answers: ['に', 'ひ', 'じつ'],
  ),
  Kanji(
    translation: NA.t('月'),
    kanji: '月',
    onYomi: 'ゲツ / ガツ',
    kunYomi: 'つき',
    phrases: ['月曜日', '一月', '今月'],
    answers: ['げつ', 'がつ', 'げつ'],
  ),
  Kanji(
    translation: NA.t('火'),
    kanji: '火',
    onYomi: 'カ',
    kunYomi: 'ひ / ほ-のお',
    phrases: ['火曜日', '火山', '火'],
    answers: ['か', 'か', 'ひ'],
  ),
  Kanji(
    translation: NA.t('水'),
    kanji: '水',
    onYomi: 'スイ',
    kunYomi: 'みず / みず-うみ',
    phrases: ['水曜日', '水'],
    answers: ['すい', 'みず'],
  ),
  Kanji(
    translation: NA.t('木'),
    kanji: '木',
    onYomi: 'ボク / モク',
    kunYomi: 'き / こ-',
    phrases: ['木', '木曜日'],
    answers: ['き', 'もく'],
  ),
  Kanji(
    translation: NA.t('金'),
    kanji: '金',
    onYomi: 'キン / コン / ゴン',
    kunYomi: 'かね / かな- / がね',
    phrases: ['お金', '金', '金曜日'],
    answers: ['かね', 'きん', 'きん'],
  ),
  Kanji(
    translation: NA.t('土'),
    kanji: '土',
    onYomi: 'ド / ト',
    kunYomi: 'つち',
     phrases: ['土', '土曜日'],
    answers: ['つち', 'ど'],
  ),
  Kanji(
    translation: NA.t('曜'),
    kanji: '曜',
    onYomi: 'ヨウ',
    kunYomi: '',
    phrases: ['月曜日'],
    answers: ['よう'],
  ),
   Kanji(
    translation: NA.t('年'),
    kanji: '年',
    onYomi: 'ネン',
    kunYomi: 'とし',
    phrases: ['年', '二千年', '来年'],
    answers: ['とし', 'ねん', 'ねん'],
  ),
  Kanji(
    translation: NA.t('上'),
    kanji: '上',
    onYomi: 'ジョウ / ショウ',
    kunYomi: 'うえ / あ-がる / あ-げる\nのぼ-る / のぼ-せる / のぼ-す',
    phrases: ['上がる', '水上スキー'],
    answers: ['あ', 'じょう'],
  ),
  Kanji(
    translation: NA.t('下'),
    kanji: '下',
    onYomi: 'カ / ゲ',
    kunYomi: 'した / しも / もと\nさ-がる / さ-げる / くだ-る\nくだ-す / くだ-さる',
    phrases: ['下がる', '上下', '下'],
    answers: ['さ', 'げ', 'した'],
  ),
  Kanji(
    translation: NA.t('中'),
    kanji: '中',
    onYomi: 'チュウ',
    kunYomi: 'なか',
    phrases: ['一日中', '中'],
    answers: ['じゅう', 'なか'],
  ),
  Kanji(
    translation: NA.t('外'),
    kanji: '外',
    onYomi: 'ガイ',
    kunYomi: 'そと / ほか / はず-す / はず-れる',
    phrases: ['外', '外国',],
    answers: ['そと', 'がい'],
  ),
  Kanji(
    translation: NA.t('前'),
    kanji: '前',
    onYomi: 'ゼン',
    kunYomi: 'まえ',
    phrases: ['前', '三日前'],
    answers: ['まえ', 'まえ'],
  ),
  Kanji(
    translation: NA.t('後'),
    kanji: '後',
    onYomi: 'ゴ / コウ',
    kunYomi: 'うし-ろ / あと / のち',
    phrases: ['後', '後ろ'],
    answers: ['あと', 'うし'],
  ),
  Kanji(
    translation: NA.t('右'),
    kanji: '右',
    onYomi: 'ウ / ユウ',
    kunYomi: 'みぎ',
    phrases: ['右', '右手', '左右'],
    answers: ['みぎ', 'みぎ', 'ゆう'],
  ),
  Kanji(
    translation: NA.t('左'),
    kanji: '左',
    onYomi: 'サ / シャ',
    kunYomi: 'ひだり',
    phrases: ['左', '左手'],
    answers: ['ひだり', 'ひだり'],
  ),
  Kanji(
    translation: NA.t('大'),
    kanji: '大',
    onYomi: 'ダイ / タイ',
    kunYomi: 'おお- / おお(きい)',
    phrases: ['大きい', '大学', '大会'],
    answers: ['おお', 'だい', 'たい'],
  ),
  Kanji(
    translation: NA.t('小'),
    kanji: '小',
    onYomi: 'ショウ',
    kunYomi: 'ちい(さい) / こ- / -こ / お-, さ-',
    phrases: ['小さい', '小川', '小犬'],
    answers: ['ちい', 'お', 'こ'],
  ),
  Kanji(
    translation: NA.t('長'),
    kanji: '長',
    onYomi: 'チョウ',
    kunYomi: 'なが- / -なが(い)',
    phrases: ['長い', '学長'],
    answers: ['なが', 'ちょう'],
  ),
  Kanji(
    translation: NA.t('短'),
    kanji: '短',
    onYomi: 'タン',
    kunYomi: 'みじか- / -みじか(い)',
    phrases: ['短い'],
    answers: ['みじか'],
  ),
  Kanji(
    translation: NA.t('高'),
    kanji: '高',
    onYomi: 'コウ',
    kunYomi: 'たか-い / たか / -だか\nたか.まる / たか.める',
    phrases: ['高い', '円高'],
    answers: ['たか', 'だか'],
  ),
  Kanji(
    translation: NA.t('安'),
    kanji: '安',
    onYomi: 'アン',
    kunYomi: 'やす-い / やす-まる / やす\nやす.らか',
    phrases: ['安い', '安全'],
    answers: ['やす', 'あん'],
  ),
  Kanji(
    translation: NA.t('新'),
    kanji: '新',
    onYomi: 'しん / さん',
    kunYomi: 'アタラシイ',
    phrases: ['新しい', '新人', '新年'],
    answers: ['あたら', 'しん', 'しん'],
  ),
  Kanji(
    translation: NA.t('古'),
    kanji: '古',
    onYomi: 'こ',
    kunYomi: 'フルイ',
    phrases: ['古い'],
    answers: ['ふる'],
  ),
  Kanji(
    translation: NA.t('暑'),
    kanji: '暑',
    onYomi: 'しょ',
    kunYomi: 'アツイ',
     phrases: ['暑い'],
    answers: ['あつ'],
  ),
  Kanji(
    translation: NA.t('寒'),
    kanji: '寒',
    onYomi: 'かん',
    kunYomi: 'サムイ',
    phrases: ['寒い'],
    answers: ['さむ'],
  ),
  Kanji(
    translation: NA.t('明'),
    kanji: '明',
    onYomi: 'メイ / ミョウ',
    kunYomi: 'あ-かり / あか-るい / あか-るむ\nあか-らむ / あき-らか / あ-ける\nあ-く / あ-くる / あ-かす',
    phrases: ['明かり', '明き', '明日'],
    answers: ['あ', 'あ', 'あした'],
  ),
  Kanji(
    translation: NA.t('暗'),
    kanji: '暗',
    onYomi: 'アン',
    kunYomi: 'くら-い',
    phrases: ['暗い', '暗れる'],
    answers: ['くらい', 'く'],
  ),
  Kanji(
    translation: NA.t('忙'),
    kanji: '忙',
    onYomi: 'ボウ',
    kunYomi: 'いそが-しい',
    phrases: ['忙しい', '大忙し', '忙しげ'],
    answers: ['いそが', 'いそが', 'せわ'],
  ),
  Kanji(
    translation: NA.t('静'),
    kanji: '静',
    onYomi: 'セイ / ジョウ',
    kunYomi: 'しず- / -しず(か) / -しず(まる)\n-しず(める)',
    phrases: ['静か', '静まる'],
    answers: ['しず', 'しず'],
  ),
  Kanji(
    translation: NA.t('難'),
    kanji: '難',
    onYomi: 'ナン',
    kunYomi: 'かた-い / -がたい',
    phrases: ['難しい', '難', '難い'],
    answers: ['むずか', 'なん', 'にく'],
  ),
  Kanji(
    translation: NA.t('簡'),
    kanji: '簡',
    onYomi: 'カン',
    kunYomi: 'えら-ぶ / かんたん',
    phrases: ['簡明'],
    answers: ['かん'],
  ),
  Kanji(
    translation: NA.t('好'),
    kanji: '好',
    onYomi: 'コウ',
    kunYomi: 'この-む / -この(む)',
    phrases: ['好い', '大好き', '好む'],
    answers: ['よ', 'す', 'この'],
  ),
  Kanji(
    translation: NA.t('嫌'),
    kanji: '嫌',
    onYomi: 'ケン',
    kunYomi: 'きら-う / -ぎら(い)',
    phrases: ['嫌い', '嫌う', '嫌'],
    answers: ['きら', 'きら', 'いや'],
  ),
  Kanji(
    translation: NA.t('多'),
    kanji: '多',
    onYomi: 'タ',
    kunYomi: 'おお(い) / まさ(に) / まさ(る)',
    phrases: ['多分', '多大'],
    answers: ['た', 'た'],
  ),
  Kanji(
    translation: NA.t('少'),
    kanji: '少',
    onYomi: 'ショウ',
    kunYomi: 'すく.ない / すこ(し)',
    phrases: ['少し', '少年', '少女'],
    answers: ['すこ', 'しょう', 'しょう'],
  ),
  Kanji(
    translation: NA.t('色'),
    kanji: '色',
    onYomi: 'ショク',
    kunYomi: 'いろ',
    phrases: ['色'],
    answers: ['いろ'],
  ),
  Kanji(
    translation: NA.t('黒'),
    kanji: '黒',
    onYomi: 'コク',
    kunYomi: 'くろ / くろ(い)',
    phrases: ['黒い', '黒色'],
    answers: ['くろ', 'くろ'],
  ),
  Kanji(
    translation: NA.t('白'),
    kanji: '白',
    onYomi: 'ハク / ビャク',
    kunYomi: 'しろ / しろ(い)',
    phrases: ['白い', '明白'],
    answers: ['しろ', 'はく',],
  ),
  Kanji(
    translation: NA.t('赤'),
    kanji: '赤',
    onYomi: 'セキ / シャク',
    kunYomi: 'あか / あか.い / あか.らむ\nあか(らめる)',
    phrases: ['赤い', '赤ちゃん', '赤色'],
    answers: ['あか', 'あか', 'あか'],
  ),
  Kanji(
    translation: NA.t('青'),
    kanji: '青',
    onYomi: 'セイ / ショウ',
    kunYomi: 'あお / あお- / あお(い)',
    phrases: ['青い','青色'],
    answers: ['青', 'あお'],
  ),
  Kanji(
    translation: NA.t('黄'),
    kanji: '黄',
    onYomi: 'コウ',
    kunYomi: 'き / こ-',
    phrases: ['黄金', '着色'],
    answers: ['おう', 'き'],
  ),
  Kanji(
    translation: NA.t('紫'),
    kanji: '紫',
    onYomi: 'シ',
    kunYomi: 'むらさき',
    phrases: ['紫色', '大紫'],
    answers: ['むらさき', 'むらさき'],
  ),
  Kanji(
    translation: NA.t('茶'),
    kanji: '茶',
    onYomi: 'チャ / サ',
    kunYomi: 'ちゃ',
    phrases: ['お茶', '茶色'],
    answers: ['ちゃ', 'ちゃ'],
  ),
  Kanji(
    translation: NA.t('食'),
    kanji: '食',
    onYomi: 'ショク / ジキ',
    kunYomi: 'く(う) / く(らう) / た(べる)',
    phrases: ['食べる', '食べ物'],
    answers: ['た','た'],
  ),
  Kanji(
    translation: NA.t('飲'),
    kanji: '飲',
    onYomi: 'イン',
    kunYomi: 'の(む)',
    phrases: ['飲み物', '飲み'],
    answers: ['の', 'の'],
  ),
  Kanji(
    translation: NA.t('買'),
    kanji: '買',
    onYomi: 'バイ',
    kunYomi: 'か-う',
    phrases: ['買い物', '買い手', '買う'],
    answers: ['か', 'か', 'か'],
  ),
  Kanji(
    translation: NA.t('見'),
    kanji: '見',
    onYomi: 'ケン',
    kunYomi: 'み-る / み-える / み-せる',
    phrases: ['見える', '見る', '一見'],
    answers: ['み', 'み', 'けん'],
  ),
  Kanji(
    translation: NA.t('聞'),
    kanji: '聞',
    onYomi: 'ブン / モン',
    kunYomi: 'き-く / き-こえる',
    phrases: ['聞く', '聞こえる'],
    answers: ['き', 'き'],
  ),
  Kanji(
    translation: NA.t('話'),
    kanji: '話',
    onYomi: 'ワ',
    kunYomi: 'はな-す / はなし',
    phrases: ['話す'],
    answers: ['はな'],
  ),
  Kanji(
    translation: NA.t('読'),
    kanji: '読',
    onYomi: 'ドク / トク',
    kunYomi: 'よ-む',
    phrases: ['読み', '読む', '読み方'],
    answers: ['よ', 'よ', 'よ'],
  ),
  Kanji(
    translation: NA.t('書'),
    kanji: '書',
    onYomi: 'ショ',
    kunYomi: 'か-く',
    phrases: ['書', '文書'],
    answers: ['ふみ', 'しょ'],
  ),
  Kanji(
    translation: NA.t('入'),
    kanji: '入',
    onYomi: 'ニュウ',
    kunYomi: 'い-る / -い-る / い-れる\n-い-れ',
    phrases: ['入', '入力'],
    answers: ['いり', 'にゅう'],
  ),
  Kanji(
    translation: NA.t('出'),
    kanji: '出',
    onYomi: 'シュツ',
    kunYomi: 'で-る / -でる / だ-す\n-だす / だ-れる / -だれる',
    phrases: ['出る', '出し', '出かける'],
    answers: ['で', 'だ', 'で'],
  ),
  Kanji(
    translation: NA.t('立'),
    kanji: '立',
    onYomi: 'リツ / リュウ',
    kunYomi: 'た(つ) / た(ち-) / た(てる)\nたて- / たてあ(げる) / たつ',
    phrases: ['立ち', '立つ'],
    answers: ['た', 'た'],
  ),
  Kanji(
    translation: NA.t('座'),
    kanji: '座',
    onYomi: 'ザ',
    kunYomi: 'すわ(る)',
    phrases: ['座る', '一座', '口座'],
    answers: ['すわ', 'ざ', 'ざ'],
  ),
  Kanji(
    translation: NA.t('休'),
    kanji: '休',
    onYomi: 'キュウ',
    kunYomi: 'やす(む) / やす.まる / やす(める)',
    phrases: ['休み', '休む', '休日'],
    answers: ['やす', 'やす', 'きゅう'],
  ),
  Kanji(
    translation: NA.t('行'),
    kanji: '行',
    onYomi: 'コウ / ギョウ / アン',
    kunYomi: 'い(く) / ゆ(く) / おこな(う)',
    phrases: ['行き', '行方', '行う'],
    answers: ['い', 'ゆく', 'おこな'],
  ),
  Kanji(
    translation: NA.t('来'),
    kanji: '来',
    onYomi: 'ライ / タイ',
    kunYomi: 'く(る) / きた(る) / きた(す)\nき(たす) / き(たる) / き',
    phrases: ['来月', '来日'],
    answers: ['らい', 'らい'],
  ),
  Kanji(
    translation: NA.t('帰'),
    kanji: '帰',
    onYomi: 'キ',
    kunYomi: 'かえ(る) / かえ(す)',
    phrases: ['帰り', '帰国', '日帰り'],
    answers: ['かえ', 'き', 'がえ'],
  ),
  Kanji(
    translation: NA.t('開'),
    kanji: '開',
    onYomi: 'カイ',
    kunYomi: 'あ(く) / あ(ける) / ひら(く)\nひら(ける) / さか(る) / さか(ん)',
    phrases: ['開く', '開く'],
    answers: ['あ', 'ひら'],
  ),
  Kanji(
    translation: NA.t('閉'),
    kanji: '閉',
    onYomi: 'ヘイ',
    kunYomi: 'と(じる) / と(ざす) / し(める)\nし(まる)',
    phrases: ['閉まる', '閉じる', '閉山'],
    answers: ['し', 'と', 'へい'],
  ),
  Kanji(
    translation: NA.t('山'),
    kanji: '山',
    onYomi: 'サン',
    kunYomi: 'やま',
    phrases: ['山', 'ふじ山'],
    answers: ['やま', 'さん'],
  ),
  Kanji(
    translation: NA.t('今'),
    kanji: '今',
    onYomi: 'コン',
    kunYomi: 'いま',
    phrases: ['今月', '今に', '今日'],
    answers: ['こん', 'いま', 'きょう'],
  ),
   Kanji(
    translation: NA.t('川'),
    kanji: '川',
    onYomi: 'セン',
    kunYomi: 'かわ',
    phrases: ['川', '山川さん'],
    answers: ['かわ', 'かわ'],
  ),
    Kanji(
    translation: NA.t('田'),
    kanji: '田',
    onYomi: 'デン',
    kunYomi: 'た',
    phrases: ['山田さん', '水田', '田'],
    answers: ['だ', 'でん', 'だ'],
  ),
     Kanji(
    translation: NA.t('分'),
    kanji: '分',
    onYomi: 'ブン / フン(ープン)',
    kunYomi: 'わーける / わーかる',
    phrases: ['分ける', '十分', '分かる'],
    answers: ['わ', 'ぷん', 'わ'],
  ),

  
];

class Kanji {
  final String kanji;
  final String onYomi;
  final String kunYomi;
  final String translation;
  final List<String> phrases;
  final List<String> answers;

  Kanji({
    required this.translation,
    required this.kanji,
    required this.onYomi,
    required this.kunYomi,
    required this.phrases,
    required this.answers,
  });
}
