class NareNumber {
  final int digit;
  final String written;
  late String alternate;

  NareNumber({required this.digit, required this.written, this.alternate = ''}) {
    if (this.alternate.length == 0) {
      this.alternate = this.written;
    }
  }
}

final List<NareNumber> nativeNumberBank = [
  NareNumber(digit: 1, written: 'ひとつ', alternate: '一つ'),
  NareNumber(digit: 2, written: 'ふたつ', alternate: '二つ'),
  NareNumber(digit: 3, written: 'みっつ', alternate: '三つ'),
  NareNumber(digit: 4, written: 'よっつ', alternate: '四つ'),
  NareNumber(digit: 5, written: 'いつつ', alternate: '五つ'),
  NareNumber(digit: 6, written: '여섯'),
  NareNumber(digit: 7, written: '일곱'),
  NareNumber(digit: 8, written: '여덟'),
  NareNumber(digit: 9, written: '아홉'),
  NareNumber(digit: 10, written: '열'),
  NareNumber(digit: 11, written: '열하나', alternate: '열한'),
  NareNumber(digit: 12, written: '열둘', alternate: '열두'),
  NareNumber(digit: 13, written: '열셋', alternate: '열세'),
  NareNumber(digit: 14, written: '열넷', alternate: '열네'),
  NareNumber(digit: 15, written: '열다섯'),
  NareNumber(digit: 16, written: '열여섯'),
  NareNumber(digit: 17, written: '열일곱'),
  NareNumber(digit: 18, written: '열여덟'),
  NareNumber(digit: 19, written: '열아홉'),
  NareNumber(digit: 20, written: '스물'),
  NareNumber(digit: 21, written: '스물하나', alternate: '스물한'),
  NareNumber(digit: 22, written: '스물둘', alternate: '스물두'),
  NareNumber(digit: 23, written: '스물셋', alternate: '스물세'),
  NareNumber(digit: 24, written: '스물넷', alternate: '스물네'),
  NareNumber(digit: 25, written: '스물다섯'),
  NareNumber(digit: 26, written: '스물여섯'),
  NareNumber(digit: 27, written: '스물일곱'),
  NareNumber(digit: 28, written: '스물여덟'),
  NareNumber(digit: 29, written: '스물아홉'),
  NareNumber(digit: 30, written: '서른'),
  NareNumber(digit: 31, written: '서른하나', alternate: '서른한'),
  NareNumber(digit: 32, written: '서른둘', alternate: '서른두'),
  NareNumber(digit: 33, written: '서른셋', alternate: '서른세'),
  NareNumber(digit: 34, written: '서른넷', alternate: '서른네'),
  NareNumber(digit: 35, written: '서른다섯'),
  NareNumber(digit: 36, written: '서른여섯'),
  NareNumber(digit: 37, written: '서른일곱'),
  NareNumber(digit: 38, written: '서른여덟'),
  NareNumber(digit: 39, written: '서른아홉'),
  NareNumber(digit: 40, written: '마흔'),
  NareNumber(digit: 41, written: '마흔하나', alternate: '마흔한'),
  NareNumber(digit: 42, written: '마흔둘', alternate: '마흔두'),
  NareNumber(digit: 43, written: '마흔셋', alternate: '마흔세'),
  NareNumber(digit: 44, written: '마흔넷', alternate: '마흔네'),
  NareNumber(digit: 45, written: '마흔다섯'),
  NareNumber(digit: 46, written: '마흔여섯'),
  NareNumber(digit: 47, written: '마흔일곱'),
  NareNumber(digit: 48, written: '마흔여덟'),
  NareNumber(digit: 49, written: '마흔아홉'),
  NareNumber(digit: 50, written: '쉰'),
  NareNumber(digit: 51, written: '쉰하나', alternate: '쉰한'),
  NareNumber(digit: 52, written: '쉰둘', alternate: '쉰두'),
  NareNumber(digit: 53, written: '쉰셋', alternate: '쉰세'),
  NareNumber(digit: 54, written: '쉰넷', alternate: '쉰네'),
  NareNumber(digit: 55, written: '쉰다섯'),
  NareNumber(digit: 56, written: '쉰여섯'),
  NareNumber(digit: 57, written: '쉰일곱'),
  NareNumber(digit: 58, written: '쉰여덟'),
  NareNumber(digit: 59, written: '쉰아홉'),
  NareNumber(digit: 60, written: '예순'),
  NareNumber(digit: 61, written: '예순하나', alternate: '예순한'),
  NareNumber(digit: 62, written: '예순둘', alternate: '예순두'),
  NareNumber(digit: 63, written: '예순셋', alternate: '예순세'),
  NareNumber(digit: 64, written: '예순넷', alternate: '예순네'),
  NareNumber(digit: 65, written: '예순다섯'),
  NareNumber(digit: 66, written: '예순여섯'),
  NareNumber(digit: 67, written: '예순일곱'),
  NareNumber(digit: 68, written: '예순여덟'),
  NareNumber(digit: 69, written: '예순아홉'),
  NareNumber(digit: 70, written: '일흔'),
  NareNumber(digit: 71, written: '일흔하나', alternate: '일흔한'),
  NareNumber(digit: 72, written: '일흔둘', alternate: '일흔두'),
  NareNumber(digit: 73, written: '일흔셋', alternate: '일흔세'),
  NareNumber(digit: 74, written: '일흔넷', alternate: '일흔네'),
  NareNumber(digit: 75, written: '일흔다섯'),
  NareNumber(digit: 76, written: '일흔여섯'),
  NareNumber(digit: 77, written: '일흔일곱'),
  NareNumber(digit: 78, written: '일흔여덟'),
  NareNumber(digit: 79, written: '일흔아홉'),
  NareNumber(digit: 80, written: '여든'),
  NareNumber(digit: 81, written: '여든하나', alternate: '여든한'),
  NareNumber(digit: 82, written: '여든둘', alternate: '여든두'),
  NareNumber(digit: 83, written: '여든셋', alternate: '여든세'),
  NareNumber(digit: 84, written: '여든넷', alternate: '여든네'),
  NareNumber(digit: 85, written: '여든다섯'),
  NareNumber(digit: 86, written: '여든여섯'),
  NareNumber(digit: 87, written: '여든일곱'),
  NareNumber(digit: 88, written: '여든여덟'),
  NareNumber(digit: 89, written: '여든아홉'),
  NareNumber(digit: 90, written: '아흔'),
  NareNumber(digit: 91, written: '아흔하나', alternate: '아흔한'),
  NareNumber(digit: 92, written: '아흔둘', alternate: '아흔두'),
  NareNumber(digit: 93, written: '아흔셋', alternate: '아흔세'),
  NareNumber(digit: 94, written: '아흔넷', alternate: '아흔네'),
  NareNumber(digit: 95, written: '아흔다섯'),
  NareNumber(digit: 96, written: '아흔여섯'),
  NareNumber(digit: 97, written: '아흔일곱'),
  NareNumber(digit: 98, written: '아흔여덟'),
  NareNumber(digit: 99, written: '아흔아홉'),
];

final List<NareNumber> sinoNumberBank = [
  NareNumber(digit: 1, written: 'れい', alternate: '零'),
  NareNumber(digit: 1, written: 'いち', alternate: '一'),
  NareNumber(digit: 2, written: 'に', alternate: '二'),
  NareNumber(digit: 3, written: 'さん', alternate: '三'),
  NareNumber(digit: 4, written: 'よん', alternate: '四'),
  NareNumber(digit: 5, written: 'ご', alternate: '五'),
  NareNumber(digit: 6, written: 'ろく', alternate: '六'),
  NareNumber(digit: 7, written: 'なな', alternate: '七'),
  NareNumber(digit: 8, written: 'はち', alternate: '八'),
  NareNumber(digit: 9, written: 'きゅう', alternate: '九'),
  NareNumber(digit: 10, written: 'じゅう', alternate: '十'),
  NareNumber(digit: 11, written: 'じゅういち', alternate: '十一'),
   NareNumber(digit: 12, written: 'じゅう', alternate: '十二'),
  NareNumber(digit: 100, written: 'ひゃくに', alternate: '百'),
  NareNumber(digit: 1000, written: 'せん', alternate: '千'),
];

final List<NareNumber> saiNumberBank = [
  NareNumber(digit: 0, written: '', alternate: ''),
  NareNumber(digit: 1, written: 'いっさい', alternate: '一歳'),
  NareNumber(digit: 2, written: 'にさい', alternate: '二歳'),
  NareNumber(digit: 3, written: 'さんさい', alternate: '三歳'),
  NareNumber(digit: 4, written: 'よんさい', alternate: '四歳'),
  NareNumber(digit: 5, written: 'ごさい', alternate: '五歳'),
  NareNumber(digit: 6, written: 'ろくさい', alternate: '六歳'),
  NareNumber(digit: 7, written: 'ななさい', alternate: '七歳'),
  NareNumber(digit: 8, written: 'はっさい', alternate: '八歳'),
  NareNumber(digit: 9, written: 'きゅうさい', alternate: '九歳'),
];
